<?php if ((int) $show_featured_image): ?> 
    <?php $imageArgs = array('echo' => false, 'size' => $thumbnail_dimensions); ?>
    <?php $image = cbp_get_the_image($imageArgs); ?>
    <?php if (isset($image) && $image): ?>
        <div class="two fifths mobile <?php echo $this->getPrefix(); ?>-widget-post-image pad-top double-pad-right">
            <?php echo $image; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>

<div class="three fifths mobile">
<<?php echo $post_title_size; ?>>
<?php if ((int) $title_link_to_post): ?>
    <a href="<?php echo get_permalink($post->ID); ?>"><?php the_title(); ?></a>
<?php else: ?>
    <?php the_title(); ?>
<?php endif; ?>
</<?php echo $post_title_size; ?>>
<?php if ((int) $show_subtitle): ?> 
    <?php $subtitle = get_the_subtitle(); ?>
    <?php if ($subtitle): ?>
        <div class="ch-border-title">
            <?php echo $subtitle; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
<div class="<?php echo $this->getPrefix(); ?>-widget-post-meta-data">
    <?php if ((int) $show_post_date): ?> 
        <?php $postDateIcon = (int) $show_post_date_icon ? '<i class="fa fa-calendar"></i> ' : ''; ?> 
        <span class="<?php echo $this->getPrefix(); ?>-widget-post-meta-date">
            <?php echo $postDateIcon; ?><?php echo date_i18n($post_date_format, strtotime($post->post_date)); ?>
        </span>
    <?php endif; ?>
    <?php if ((int) $show_comment_count): ?> 
        <span class="<?php echo $this->getPrefix(); ?>-widget-post-meta-comments">
            <?php $commentIcon = (int) $show_comment_icon ? '<i class="fa fa-comments"></i> ' : ''; ?> 
            <?php echo $commentIcon; ?>(<?php echo $post->comment_count; ?>)
        </span>
    <?php endif; ?>
    <?php if ((int) $show_tags): ?>
        <?php $posttags = get_the_tags(); ?>
        <?php if ($posttags) : ?>
            <span class="<?php echo $this->getPrefix(); ?>-widget-post-meta-tags">
                <?php $tagsIcon = (int) $show_tags_icon ? '<i class="fa fa-tags"></i> ' : ''; ?> 
                <?php echo $tagsIcon; ?>
                <?php if ((int) $tags_is_link): ?>
                    <?php foreach ($posttags as $tag) : ?>
                        <a href="<?php echo get_tag_link($tag->term_id); ?>"><?php echo $tag->name; ?></a>
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php foreach ($posttags as $tag) : ?>
                        <?php echo $tag->name; ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </span>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ((int) $show_author): ?>
        <?php if ((int) $author_is_link): ?>
            <span class="<?php echo $this->getPrefix(); ?>-widget-post-meta-author">
                <?php echo $this->translate('by'); ?> <a href="<?php echo get_author_posts_url(get_the_author_meta('ID')); ?>">
                    <?php the_author_meta('display_name'); ?>
                </a>
            </span>
        <?php else: ?>
            <span class="<?php echo $this->getPrefix(); ?>-widget-post-meta-author">
                <?php echo $this->translate('by'); ?> <?php the_author_meta('display_name'); ?>
            </span>
        <?php endif; ?>
    <?php endif; ?>
</div>

<div class="<?php echo $this->getPrefix(); ?>-widget-post-content">
    <?php echo CbpUtils::trimmer(strip_shortcodes(get_the_content()), $number_of_characters); ?>
</div>
<?php if ((int) $use_button_link): ?>
    <div class="<?php echo $this->getPrefix(); ?>-widget-post-link double-pad-top">
        <a class="cbp_widget_link" href="<?php echo get_permalink(); ?>"><?php echo $link_text; ?></a>
    </div>
<?php endif; ?>
</div>
